### ISSUE TITLE
How to use trained model?

### ISSUE THREAD

**Issue by Metal-joker** [andrejonasson/question_answering#1]
I trained model with `python main.py` and it is stored in checkpoint folder, but how can I use this model to answer questions?

**Comment by andrejonasson** [comment]
If you used the default settings then you should only need to run:

``` sh
python main.py --mode shell --model_name <MODEL_NAME>
```

where you would replace `<MODEL_NAME>` with the `model_name` hyperparameter in flags_0.json in your checkpoints folder (it will have the same name as your folder name - and by default is a timestamp like 180117_075832.

If you do not run default settings you would need to specify the parameters again as arguments. I may make this more convenient in the future.

Note that I am still exploring the hyperparameters, so the default settings will not get more than within the 50-70 F1 range.
