### ISSUE TITLE
TypeError : dcnplus_encode() got an unexpected keyword argument 'final_input_keep_prob'

### ISSUE THREAD

**Issue by kneehit** [andrejonasson/question_answering#3]
I get the above mentioned error when I try to train dcnplus model. Doesn't occur for dcn model. 
I temporarily resolved it by modifying dcnplus_encode() to include a dummy optional argument 'final_input_keep_prob'.  [https://github.com/andrejonasson/dynamic-coattention-network-plus/blob/edfbc6f1575c43b8e987c5bbb05a895993efa364/question_answering/networks/dcn_plus.py#L152](url)

**Comment by andrejonasson** [comment]
This should be fixed now. Thanks. I had committed some temp changes (searching for proper dropout configuration) alongside proper changes.
