### ISSUE TITLE
Not compatible with tensorflow 1.5?

### ISSUE THREAD

**Issue by NewEnglandML** [andrejonasson/question_answering#6]
t is not compatible with tensorflow v.>=1.5 ?

**Comment by andrejonasson** [comment]
I'll look into this as soon as I can. It might be a while since I just moved to another country.

**Comment by andrejonasson** [comment]
This is updated to work with TF 1.10 now. I unfortunately used tf flags for this project instead of argparse and there was a change in tf.flags that made it incompatible with versions <1.5
