### ISSUE TITLE
Reinforcement Learning Loss

### ISSUE THREAD

**Issue by mehdimashayekhi** [andrejonasson/question_answering#8]
Hi, Really appreciate sharing this. I am learning a lot! Just by skimming through it, I don't see the reinforcement learning loss as mentioned in the paper, I just see Cross Entropy loss. Am I right? do you plan adding it too?

**Comment by andrejonasson** [comment]
Hi, thanks for your interest in the project. Yes, you are correct, this is mentioned in the README. There are no plans to add the reinforcement learning loss. If memory serves me right the RL loss was a minor improvement to the model in comparison with the other improvements they implemented (CoVe, two layer coattention etc.).
